apiVersion: v1
kind: Secret
metadata:
  name: benchmark-secrets
type: Opaque
stringData:
  # Redis configuration
  redis-host: ""
  redis-port: "6739"
  redis-user: ""
  redis-auth: ""
  # MongoDB configuration
  mongo-host: ""
  mongo-port: "27017"
  mongo-user: ""
  mongo-auth: ""
  mongo-read-preference: "primary"
  mongo-write-concern: "1"
  # MongoDB Atlas configuration
  embedding-field-name: "embedding"
  atlas-db-name: "vector-db"
  atlas-collection-name: "vector-collection"
  atlas-vector-search-index-name: "vector-index"
  # Benchmark configuration
  bench-datasets: "gist-960-euclidean"
  bench-engines: "redis"

